### ISSUE TITLE
[Bug]: PlotCraft-Fixer 调用 RemoteCallAPI 异常

### ISSUE THREAD

**Issue by XT-xiaotong** [engsr6982/PlotCraft#10]
### Describe the bug

11:22:22.495 ERROR [legacy-script-engine-quickjs] Event Callback Failed!
11:22:22.495 ERROR [legacy-script-engine-quickjs] C++ Uncaught Exception Detected!
11:22:22.495 ERROR [legacy-script-engine-quickjs] bad variant access
11:22:22.495 ERROR [legacy-script-engine-quickjs] [failed to obtain stacktrace]
11:22:22.495 ERROR [legacy-script-engine-quickjs] In Event: onPistonTryPush
11:22:22.495 ERROR [legacy-script-engine-quickjs] In Plugin: PlotCraft-Fixer 

### To Reproduce

活塞推动边框后报错

### Expected behavior

活塞推动边框后报错

**Comment by engsr6982** [comment]
建议移除此（PlotCraft-Fixer.js）插件，后续不再附带 RemoteCallAPI
