### ISSUE TITLE
[Bug]: 加载报错

### ISSUE THREAD

**Issue by wjh1507** [engsr6982/PlotCraft#21]
### Describe the bug

08:54:16.637 ERROR [LeviLamina] Failed to load mod PlotCraft
08:54:16.637 ERROR [LeviLamina] Reflection error in field 'economy.kit':
08:54:16.637 ERROR [LeviLamina] C++ Exception: std::bad_optional_access, from <PlotCraft>:
08:54:16.637 ERROR [LeviLamina] Bad optional access

### To Reproduce

![image](https://github.com/user-attachments/assets/0eae22ae-7004-4e5b-b515-d9f1e1b8cea7)

### Expected behavior

08:54:16.637 ERROR [LeviLamina] Failed to load mod PlotCraft
08:54:16.637 ERROR [LeviLamina] Reflection error in field 'economy.kit':
08:54:16.637 ERROR [LeviLamina] C++ Exception: std::bad_optional_access, from <PlotCraft>:
08:54:16.637 ERROR [LeviLamina] Bad optional access

### Screenshots

![屏幕截图 2024-10-31 085654](https://github.com/user-attachments/assets/99b425f3-9cc2-4d75-b9a6-aa044803d1e0)

### Platform

win11

### BDS Version

1.21.3

### LeviLamina Version

0.13.5

### Version

1.2.0

**Comment by engsr6982** [comment]
检查 Config.json 的 `economy.kit` 是否正确。
`economy.kit` 只能填写 `LegacyMoney` 或 `Scoreboard`

**Comment by wjh1507** [comment]
![Screenshot_20241031_114800](https://github.com/user-attachments/assets/ffa3a98e-66e3-433c-bf65-8ad4bb3ea19c)

**Comment by engsr6982** [comment]
> ![Screenshot_20241031_114800](https://github.com/user-attachments/assets/ffa3a98e-66e3-433c-bf65-8ad4bb3ea19c)
> 
> 

注意大小写，magic_enum 转换枚举对大小写敏感
