### ISSUE TITLE
新插件

### ISSUE THREAD

**Issue by shiguangjun112** [engsr6982/PlotCraft#9]
关于插件，我想询问，是否可以开发类似于Java的多世界的模组，管理员可以用指令生成一个世界，并传送到新创建的维度。
例如/mv create [name] [类型]

**Comment by engsr6982** [comment]
这不现实

1. 目前多维度只能新建维度，没有删除接口
2. 目前多维度只能通过 Amulet 这类软件进行编辑，且目前只能重置区块，无法移除维度
3. 服务端创建新维度后，必须得依赖 MoreDimension 才能切换维度，您无法脱离这个插件进行维度传送
4. BDS 的性能有限，维度过多会增大 BDS 的压力

**Comment by shiguangjun112** [comment]
> 这不现实
> 
> 1. 目前多维度只能新建维度，没有删除接口
> 2. 目前多维度只能通过 Amulet 这类软件进行编辑，且目前只能重置区块，无法移除维度
> 3. 服务端创建新维度后，必须得依赖 MoreDimension 才能切换维度，您无法脱离这个插件进行维度传送
> 4. BDS 的性能有限，维度过多会增大 BDS 的压力

抱歉，冒昧打扰了

**Comment by engsr6982** [comment]
如果您确实有需求，且没有以上顾虑的话
可以参照这个项目 https://github.com/engsr6982/SuperFlatDimension

根据自己的需求添加更多维度注册即可
